-- CreateTable
CREATE TABLE `cin7_purchase_order_line_items` (
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    `purchase_order_id` INTEGER NOT NULL,
    `cin7_line_item_id` INTEGER NOT NULL,
    `product_id` INTEGER NOT NULL,
    `code` VARCHAR(100) NOT NULL,
    `name` VARCHAR(255) NOT NULL,
    `qty` DECIMAL(12, 4) NOT NULL,
    `unit_price` DECIMAL(12, 4) NOT NULL,
    `discount` DECIMAL(8, 2) NOT NULL,
    `tax` DECIMAL(12, 2) NOT NULL,
    `total` DECIMAL(12, 2) NOT NULL,
    `unit_cost` DECIMAL(12, 4) NOT NULL,
    `line_item_type` VARCHAR(50) NOT NULL,
    `sort_order` INTEGER NOT NULL,
    `option1` VARCHAR(100) NULL,
    `option2` VARCHAR(100) NULL,
    `option3` VARCHAR(100) NULL,
    `style_code` VARCHAR(100) NULL,
    `barcode` VARCHAR(100) NULL,
    `tax_rule` VARCHAR(100) NULL,
    `account_code` VARCHAR(50) NULL,
    `comment` TEXT NULL,
    `synced_at` DATETIME(3) NOT NULL,
    `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `modified_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),

    INDEX `cin7_po_line_items_purchase_order_id_idx`(`purchase_order_id`),
    INDEX `cin7_po_line_items_product_id_idx`(`product_id`),
    INDEX `idx_cin7_po_line_items_synced_at`(`synced_at`),
    UNIQUE INDEX `uq_cin7_po_line_items_po_id_line_item_id`(`purchase_order_id`, `cin7_line_item_id`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `cin7_credit_note_line_items` (
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    `credit_note_id` INTEGER NOT NULL,
    `cin7_line_item_id` INTEGER NOT NULL,
    `product_id` INTEGER NOT NULL,
    `code` VARCHAR(100) NOT NULL,
    `name` VARCHAR(255) NOT NULL,
    `qty` DECIMAL(12, 4) NOT NULL,
    `unit_price` DECIMAL(12, 4) NOT NULL,
    `discount` DECIMAL(8, 2) NOT NULL,
    `tax` DECIMAL(12, 2) NOT NULL,
    `total` DECIMAL(12, 2) NOT NULL,
    `unit_cost` DECIMAL(12, 4) NOT NULL,
    `line_item_type` VARCHAR(50) NOT NULL,
    `sort_order` INTEGER NOT NULL,
    `option1` VARCHAR(100) NULL,
    `option2` VARCHAR(100) NULL,
    `option3` VARCHAR(100) NULL,
    `style_code` VARCHAR(100) NULL,
    `barcode` VARCHAR(100) NULL,
    `tax_rule` VARCHAR(100) NULL,
    `account_code` VARCHAR(50) NULL,
    `comment` TEXT NULL,
    `synced_at` DATETIME(3) NOT NULL,
    `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `modified_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),

    INDEX `cin7_cn_line_items_credit_note_id_idx`(`credit_note_id`),
    INDEX `cin7_cn_line_items_product_id_idx`(`product_id`),
    INDEX `idx_cin7_cn_line_items_synced_at`(`synced_at`),
    UNIQUE INDEX `uq_cin7_cn_line_items_cn_id_line_item_id`(`credit_note_id`, `cin7_line_item_id`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `cin7_stock_adjustment_line_items` (
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    `stock_adjustment_id` INTEGER NOT NULL,
    `cin7_line_item_id` INTEGER NOT NULL,
    `product_id` INTEGER NOT NULL,
    `code` VARCHAR(100) NOT NULL,
    `name` VARCHAR(255) NOT NULL,
    `qty` DECIMAL(12, 4) NOT NULL,
    `unit_price` DECIMAL(12, 4) NOT NULL,
    `discount` DECIMAL(8, 2) NOT NULL,
    `tax` DECIMAL(12, 2) NOT NULL,
    `total` DECIMAL(12, 2) NOT NULL,
    `unit_cost` DECIMAL(12, 4) NOT NULL,
    `line_item_type` VARCHAR(50) NOT NULL,
    `sort_order` INTEGER NOT NULL,
    `option1` VARCHAR(100) NULL,
    `option2` VARCHAR(100) NULL,
    `option3` VARCHAR(100) NULL,
    `style_code` VARCHAR(100) NULL,
    `barcode` VARCHAR(100) NULL,
    `tax_rule` VARCHAR(100) NULL,
    `account_code` VARCHAR(50) NULL,
    `comment` TEXT NULL,
    `synced_at` DATETIME(3) NOT NULL,
    `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `modified_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),

    INDEX `cin7_sa_line_items_stock_adjustment_id_idx`(`stock_adjustment_id`),
    INDEX `cin7_sa_line_items_product_id_idx`(`product_id`),
    INDEX `idx_cin7_sa_line_items_synced_at`(`synced_at`),
    UNIQUE INDEX `uq_cin7_sa_line_items_sa_id_line_item_id`(`stock_adjustment_id`, `cin7_line_item_id`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
