-- CreateTable: cin7_orders
CREATE TABLE `cin7_orders` (
    `id`              INT NOT NULL AUTO_INCREMENT,
    `cin7_id`         INT NOT NULL,
    `order_number`    VARCHAR(100) NOT NULL,
    `customer_email`  VARCHAR(255) NULL,
    `cin7_member_id`  INT NULL,
    `status`          VARCHAR(50) NOT NULL,
    `total_amount`    DECIMAL(12, 2) NOT NULL,
    `tax_total`       DECIMAL(12, 2) NOT NULL,
    `line_item_total` DECIMAL(12, 2) NOT NULL,
    `shipping_total`  DECIMAL(12, 2) NULL,
    `payment_terms`   VARCHAR(100) NULL,
    `branch_id`       INT NOT NULL,
    `currency`        VARCHAR(10) NOT NULL,
    `order_date`      DATETIME(3) NOT NULL,
    `modified_date`   DATETIME(3) NOT NULL,
    `raw_data`        JSON NOT NULL,
    `synced_at`       DATETIME(3) NOT NULL,
    `created_at`      DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updated_at`      DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),

    UNIQUE INDEX `cin7_orders_cin7_id_key` (`cin7_id`),
    INDEX `cin7_orders_customer_email_idx` (`customer_email`),
    INDEX `cin7_orders_status_idx` (`status`),
    INDEX `cin7_orders_branch_id_idx` (`branch_id`),
    INDEX `cin7_orders_order_date_idx` (`order_date`),
    INDEX `cin7_orders_modified_date_idx` (`modified_date`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable: cin7_order_line_items
CREATE TABLE `cin7_order_line_items` (
    `id`            INT NOT NULL AUTO_INCREMENT,
    `cin7_id`       INT NOT NULL,
    `order_cin7_id` INT NOT NULL,
    `product_id`    INT NOT NULL,
    `code`          VARCHAR(100) NOT NULL,
    `name`          VARCHAR(255) NOT NULL,
    `qty`           DECIMAL(12, 4) NOT NULL,
    `unit_price`    DECIMAL(12, 4) NOT NULL,
    `discount`      DECIMAL(12, 4) NOT NULL,
    `tax`           DECIMAL(12, 4) NOT NULL,
    `total`         DECIMAL(12, 4) NOT NULL,
    `raw_data`      JSON NOT NULL,
    `synced_at`     DATETIME(3) NOT NULL,
    `created_at`    DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updated_at`    DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),

    UNIQUE INDEX `cin7_order_line_items_cin7_id_key` (`cin7_id`),
    INDEX `cin7_order_line_items_order_cin7_id_idx` (`order_cin7_id`),
    INDEX `cin7_order_line_items_product_id_idx` (`product_id`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable: cin7_contacts
CREATE TABLE `cin7_contacts` (
    `id`            INT NOT NULL AUTO_INCREMENT,
    `cin7_id`       INT NOT NULL,
    `type`          VARCHAR(50) NOT NULL,
    `first_name`    VARCHAR(100) NULL,
    `last_name`     VARCHAR(100) NULL,
    `email`         VARCHAR(255) NULL,
    `phone`         VARCHAR(50) NULL,
    `mobile`        VARCHAR(50) NULL,
    `fax`           VARCHAR(50) NULL,
    `company`       VARCHAR(255) NULL,
    `website`       VARCHAR(255) NULL,
    `address1`      VARCHAR(255) NULL,
    `address2`      VARCHAR(255) NULL,
    `city`          VARCHAR(100) NULL,
    `state`         VARCHAR(100) NULL,
    `post_code`     VARCHAR(20) NULL,
    `country`       VARCHAR(100) NULL,
    `is_active`     BOOLEAN NOT NULL DEFAULT true,
    `account_code`  VARCHAR(50) NULL,
    `price_tier`    VARCHAR(50) NULL,
    `discount`      DECIMAL(8, 4) NULL,
    `credit_limit`  DECIMAL(12, 2) NULL,
    `currency_code` VARCHAR(10) NULL,
    `tax_number`    VARCHAR(50) NULL,
    `tax_rule`      VARCHAR(100) NULL,
    `note`          TEXT NULL,
    `group`         VARCHAR(100) NULL,
    `member_since`  DATETIME(3) NOT NULL,
    `created_date`  DATETIME(3) NOT NULL,
    `updated_date`  DATETIME(3) NOT NULL,
    `raw_data`      JSON NOT NULL,
    `synced_at`     DATETIME(3) NOT NULL,
    `created_at`    DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updated_at`    DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),

    UNIQUE INDEX `cin7_contacts_cin7_id_key` (`cin7_id`),
    INDEX `cin7_contacts_email_idx` (`email`),
    INDEX `cin7_contacts_company_idx` (`company`),
    INDEX `cin7_contacts_is_active_idx` (`is_active`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable: cin7_products
CREATE TABLE `cin7_products` (
    `id`                    INT NOT NULL AUTO_INCREMENT,
    `cin7_id`               INT NOT NULL,
    `name`                  VARCHAR(255) NOT NULL,
    `code`                  VARCHAR(100) NOT NULL,
    `barcode`               VARCHAR(100) NULL,
    `category`              VARCHAR(100) NULL,
    `brand`                 VARCHAR(100) NULL,
    `supplier`              VARCHAR(255) NULL,
    `supplier_id`           INT NULL,
    `description`           TEXT NULL,
    `short_description`     VARCHAR(500) NULL,
    `is_active`             BOOLEAN NOT NULL DEFAULT true,
    `type`                  VARCHAR(50) NOT NULL,
    `option1_name`          VARCHAR(50) NULL,
    `option2_name`          VARCHAR(50) NULL,
    `option3_name`          VARCHAR(50) NULL,
    `unit_price`            DECIMAL(12, 4) NOT NULL,
    `cost_price`            DECIMAL(12, 4) NULL,
    `tax_rule`              VARCHAR(100) NULL,
    `account_code`          VARCHAR(50) NULL,
    `purchase_tax_rule`     VARCHAR(100) NULL,
    `purchase_account_code` VARCHAR(50) NULL,
    `weight`                DECIMAL(10, 4) NULL,
    `cbm`                   DECIMAL(10, 4) NULL,
    `height`                DECIMAL(10, 4) NULL,
    `width`                 DECIMAL(10, 4) NULL,
    `depth`                 DECIMAL(10, 4) NULL,
    `created_date`          DATETIME(3) NOT NULL,
    `updated_date`          DATETIME(3) NOT NULL,
    `raw_data`              JSON NOT NULL,
    `synced_at`             DATETIME(3) NOT NULL,
    `created_at`            DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updated_at`            DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),

    UNIQUE INDEX `cin7_products_cin7_id_key` (`cin7_id`),
    INDEX `cin7_products_code_idx` (`code`),
    INDEX `cin7_products_barcode_idx` (`barcode`),
    INDEX `cin7_products_category_idx` (`category`),
    INDEX `cin7_products_brand_idx` (`brand`),
    INDEX `cin7_products_is_active_idx` (`is_active`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable: cin7_inventory
CREATE TABLE `cin7_inventory` (
    `id`            INT NOT NULL AUTO_INCREMENT,
    `cin7_id`       INT NOT NULL,
    `product_id`    INT NOT NULL,
    `branch_id`     INT NOT NULL,
    `code`          VARCHAR(100) NOT NULL,
    `name`          VARCHAR(255) NOT NULL,
    `barcode`       VARCHAR(100) NULL,
    `option1`       VARCHAR(100) NULL,
    `option2`       VARCHAR(100) NULL,
    `option3`       VARCHAR(100) NULL,
    `style_code`    VARCHAR(100) NULL,
    `is_active`     BOOLEAN NOT NULL DEFAULT true,
    `stock_on_hand` DECIMAL(12, 4) NOT NULL,
    `available`     DECIMAL(12, 4) NOT NULL,
    `committed`     DECIMAL(12, 4) NOT NULL,
    `incoming`      DECIMAL(12, 4) NOT NULL,
    `bin_location`  VARCHAR(100) NULL,
    `reorder_point` DECIMAL(12, 4) NULL,
    `reorder_qty`   DECIMAL(12, 4) NULL,
    `cost_price`    DECIMAL(12, 4) NULL,
    `unit_price`    DECIMAL(12, 4) NULL,
    `raw_data`      JSON NOT NULL,
    `synced_at`     DATETIME(3) NOT NULL,
    `created_at`    DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updated_at`    DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),

    UNIQUE INDEX `cin7_inventory_cin7_id_key` (`cin7_id`),
    INDEX `cin7_inventory_product_id_idx` (`product_id`),
    INDEX `cin7_inventory_branch_id_idx` (`branch_id`),
    INDEX `cin7_inventory_product_id_branch_id_idx` (`product_id`, `branch_id`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable: cin7_purchase_orders
CREATE TABLE `cin7_purchase_orders` (
    `id`               INT NOT NULL AUTO_INCREMENT,
    `cin7_id`          INT NOT NULL,
    `reference`        VARCHAR(100) NOT NULL,
    `supplier_id`      INT NULL,
    `supplier_name`    VARCHAR(255) NULL,
    `supplier_email`   VARCHAR(255) NULL,
    `status`           VARCHAR(50) NOT NULL,
    `branch_id`        INT NOT NULL,
    `tax_inclusive`    BOOLEAN NOT NULL DEFAULT false,
    `sub_total`        DECIMAL(12, 2) NOT NULL,
    `tax`              DECIMAL(12, 2) NOT NULL,
    `total`            DECIMAL(12, 2) NOT NULL,
    `currency_code`    VARCHAR(10) NOT NULL,
    `exchange_rate`    DECIMAL(12, 6) NOT NULL,
    `note`             TEXT NULL,
    `internal_note`    TEXT NULL,
    `shipping_company` VARCHAR(255) NULL,
    `shipping_method`  VARCHAR(100) NULL,
    `shipping_cost`    DECIMAL(12, 2) NULL,
    `shipping_tax`     DECIMAL(12, 2) NULL,
    `account`          VARCHAR(100) NULL,
    `required_date`    DATETIME(3) NULL,
    `completed_date`   DATETIME(3) NULL,
    `created_date`     DATETIME(3) NOT NULL,
    `updated_date`     DATETIME(3) NOT NULL,
    `raw_data`         JSON NOT NULL,
    `synced_at`        DATETIME(3) NOT NULL,
    `created_at`       DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updated_at`       DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),

    UNIQUE INDEX `cin7_purchase_orders_cin7_id_key` (`cin7_id`),
    INDEX `cin7_purchase_orders_status_idx` (`status`),
    INDEX `cin7_purchase_orders_supplier_id_idx` (`supplier_id`),
    INDEX `cin7_purchase_orders_branch_id_idx` (`branch_id`),
    INDEX `cin7_purchase_orders_created_date_idx` (`created_date`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable: cin7_credit_notes
CREATE TABLE `cin7_credit_notes` (
    `id`            INT NOT NULL AUTO_INCREMENT,
    `cin7_id`       INT NOT NULL,
    `reference`     VARCHAR(100) NOT NULL,
    `member_id`     INT NULL,
    `member_email`  VARCHAR(255) NULL,
    `member_name`   VARCHAR(255) NULL,
    `status`        VARCHAR(50) NOT NULL,
    `branch_id`     INT NOT NULL,
    `tax_inclusive` BOOLEAN NOT NULL DEFAULT false,
    `sub_total`     DECIMAL(12, 2) NOT NULL,
    `tax`           DECIMAL(12, 2) NOT NULL,
    `total`         DECIMAL(12, 2) NOT NULL,
    `currency_code` VARCHAR(10) NOT NULL,
    `exchange_rate` DECIMAL(12, 6) NOT NULL,
    `note`          TEXT NULL,
    `internal_note` TEXT NULL,
    `account`       VARCHAR(100) NULL,
    `credit_date`   DATETIME(3) NULL,
    `created_date`  DATETIME(3) NOT NULL,
    `updated_date`  DATETIME(3) NOT NULL,
    `raw_data`      JSON NOT NULL,
    `synced_at`     DATETIME(3) NOT NULL,
    `created_at`    DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updated_at`    DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),

    UNIQUE INDEX `cin7_credit_notes_cin7_id_key` (`cin7_id`),
    INDEX `cin7_credit_notes_status_idx` (`status`),
    INDEX `cin7_credit_notes_member_id_idx` (`member_id`),
    INDEX `cin7_credit_notes_branch_id_idx` (`branch_id`),
    INDEX `cin7_credit_notes_credit_date_idx` (`credit_date`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable: cin7_stock_adjustments
CREATE TABLE `cin7_stock_adjustments` (
    `id`             INT NOT NULL AUTO_INCREMENT,
    `cin7_id`        INT NOT NULL,
    `reference`      VARCHAR(100) NOT NULL,
    `branch_id`      INT NOT NULL,
    `status`         VARCHAR(50) NOT NULL,
    `note`           TEXT NULL,
    `completed_date` DATETIME(3) NULL,
    `created_date`   DATETIME(3) NOT NULL,
    `updated_date`   DATETIME(3) NOT NULL,
    `raw_data`       JSON NOT NULL,
    `synced_at`      DATETIME(3) NOT NULL,
    `created_at`     DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updated_at`     DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),

    UNIQUE INDEX `cin7_stock_adjustments_cin7_id_key` (`cin7_id`),
    INDEX `cin7_stock_adjustments_status_idx` (`status`),
    INDEX `cin7_stock_adjustments_branch_id_idx` (`branch_id`),
    INDEX `cin7_stock_adjustments_created_date_idx` (`created_date`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable: cin7_branches
CREATE TABLE `cin7_branches` (
    `id`            INT NOT NULL AUTO_INCREMENT,
    `cin7_id`       INT NOT NULL,
    `name`          VARCHAR(255) NOT NULL,
    `code`          VARCHAR(50) NULL,
    `is_active`     BOOLEAN NOT NULL DEFAULT true,
    `is_default`    BOOLEAN NOT NULL DEFAULT false,
    `address1`      VARCHAR(255) NULL,
    `address2`      VARCHAR(255) NULL,
    `city`          VARCHAR(100) NULL,
    `state`         VARCHAR(100) NULL,
    `post_code`     VARCHAR(20) NULL,
    `country`       VARCHAR(100) NULL,
    `phone`         VARCHAR(50) NULL,
    `email`         VARCHAR(255) NULL,
    `currency_code` VARCHAR(10) NULL,
    `created_date`  DATETIME(3) NOT NULL,
    `updated_date`  DATETIME(3) NOT NULL,
    `raw_data`      JSON NOT NULL,
    `synced_at`     DATETIME(3) NOT NULL,
    `created_at`    DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updated_at`    DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),

    UNIQUE INDEX `cin7_branches_cin7_id_key` (`cin7_id`),
    INDEX `cin7_branches_is_active_idx` (`is_active`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
