import { Cin7Product } from '../../types/cin7.types';
import { ProductInput } from '../../db/repositories/cin7Repo';

export function transformProduct(raw: Cin7Product, syncedAt: Date): ProductInput {
  return {
    cin7Id: raw.id,
    name: raw.name ?? null,
    code: raw.code ?? null,
    barcode: raw.barcode ?? null,
    category: raw.category ?? null,
    brand: raw.brand ?? null,
    supplier: raw.supplier ?? null,
    supplierId: raw.supplierId ?? null,
    description: raw.description ?? null,
    shortDescription: raw.shortDescription ?? null,
    isActive: raw.isActive ?? null,
    type: raw.type ?? null,
    option1Name: raw.option1Name ?? null,
    option2Name: raw.option2Name ?? null,
    option3Name: raw.option3Name ?? null,
    unitPrice: raw.unitPrice ?? null,
    unitPriceTier2: raw.unitPriceTier2 ?? null,
    unitPriceTier3: raw.unitPriceTier3 ?? null,
    unitPriceTier4: raw.unitPriceTier4 ?? null,
    unitPriceTier5: raw.unitPriceTier5 ?? null,
    unitPriceTier6: raw.unitPriceTier6 ?? null,
    unitPriceTier7: raw.unitPriceTier7 ?? null,
    unitPriceTier8: raw.unitPriceTier8 ?? null,
    unitPriceTier9: raw.unitPriceTier9 ?? null,
    unitPriceTier10: raw.unitPriceTier10 ?? null,
    costPrice: raw.costPrice ?? null,
    taxRule: raw.taxRule ?? null,
    accountCode: raw.accountCode ?? null,
    purchaseTaxRule: raw.purchaseTaxRule ?? null,
    purchaseAccountCode: raw.purchaseAccountCode ?? null,
    weight: raw.weight ?? null,
    cbm: raw.cbm ?? null,
    height: raw.height ?? null,
    width: raw.width ?? null,
    depth: raw.depth ?? null,
    srcCreatedAt: raw.createdDate ? new Date(raw.createdDate) : null,
    srcModifiedAt: raw.modifiedDate ? new Date(raw.modifiedDate) : null,
    rawData: raw,
    syncedAt,
  };
}
