-- Fix modified_at on all Facebook tables: add ON UPDATE CURRENT_TIMESTAMP(3)
-- Without this, modified_at never updates on upsert — only set on insert.

ALTER TABLE `facebook_campaigns`
  MODIFY COLUMN `modified_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3);

ALTER TABLE `facebook_adsets`
  MODIFY COLUMN `modified_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3);

ALTER TABLE `facebook_ads`
  MODIFY COLUMN `modified_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3);

ALTER TABLE `facebook_campaign_insights`
  MODIFY COLUMN `modified_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3);

ALTER TABLE `facebook_adset_insights`
  MODIFY COLUMN `modified_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3);

ALTER TABLE `facebook_ad_insights`
  MODIFY COLUMN `modified_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3);
